Repository kubesphere/test-infra, pull requests merged in 2021-07, with the labels that each got.

#2 Add initial prow cluster configs and initial prowJobs for repo kubesphere and test-infra
  config/jobs/.yamllint.conf
  config/jobs/kubesphere/console/console-presubmits.yaml
  config/jobs/kubesphere/kubesphere/kubesphere-postsubmits.yaml
  config/jobs/kubesphere/kubesphere/kubesphere-presubmits.yaml
  config/jobs/kubesphere/test-infra/test-infra-postsubmits.yaml
  config/jobs/kubesphere/test-infra/test-infra-presubmits.yaml
  config/jobs/periodics.yaml
  config/prow/cluster/cherrypicker_deployment.yaml
  config/prow/cluster/cherrypicker_service.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_rbac.yaml
  config/prow/cluster/crier_service.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/deck_rbac.yaml
  config/prow/cluster/deck_service.yaml
  config/prow/cluster/ghproxy.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_rbac.yaml
  config/prow/cluster/hook_service.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/horologium_rbac.yaml
  config/prow/cluster/horologium_service.yaml
  config/prow/cluster/needs-rebase_deployment.yaml
  config/prow/cluster/needs-rebase_service.yaml
  config/prow/cluster/prow_controller_manager_deployment.yaml
  config/prow/cluster/prow_controller_manager_rbac.yaml
  config/prow/cluster/prow_controller_manager_service.yaml
  config/prow/cluster/prowjob_customresourcedefinition.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/sinker_rbac.yaml
  config/prow/cluster/sinker_service.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/statusreconciler_rbac.yaml
  config/prow/cluster/test-pods_namespace.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/cluster/tide_rbac.yaml
  config/prow/cluster/tide_service.yaml
  config/prow/cluster/tls-ing_ingress.yaml
  config/prow/config.yaml
  config/prow/plugins.yaml
  images/build-tools/Dockerfile
  images/build-tools/bashrc
  images/build-tools/build-and-push.sh
  images/build-tools/entrypoint
Labels: size/XXL

#4 Add missing s3 credentials
  OWNERS
  config/jobs/kubesphere/test-infra/test-infra-postsubmits.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: size/S

#3 Retain LGTM through squashes
  config/prow/plugins.yaml
Labels: lgtm

#6 fix kubesphere operiodicly image building
  config/jobs/kubesphere/kubesphere/kubesphere-postsubmits.yaml
Labels: approved, size/S

#7 fix test-infra postsubmit job branch, master->main
  config/jobs/kubesphere/test-infra/test-infra-postsubmits.yaml
Labels: approved, size/XS

#8 add milestone maintainer team
  config/prow/plugins.yaml
Labels: approved, size/XS

#9 add kubebuilder bin directory to PATH
  images/build-tools/Dockerfile
Labels: approved, do-not-merge/hold, size/XS

#10 add namespace explicitly to kubectl
  config/prow/Makefile
  config/prow/update-job-config.sh
Labels: approved

#12 add documentation on how to write prowjobs
  README.md
  config/jobs/README.md
  config/prow/README.md
Labels: approved, size/L

#13 update slack reporter channel
  config/prow/plugins.yaml
Labels: approved, size/XS

#17 fix docker credential preset mount path
  config/prow/config.yaml
Labels: approved, size/XS

#18 Fix kubesphere postsubmit job typo
  config/jobs/kubesphere/kubesphere/kubesphere-postsubmits.yaml
  config/jobs/kubesphere/test-infra/test-infra-postsubmits.yaml
Labels: approved, size/M

#15 update test readme
  config/prow/README.md
Labels: approved, lgtm, size/S

#11 add console presubmit job
  config/jobs/kubesphere/console/console-presubmits.yaml
Labels: approved, lgtm, size/M

#20 fix secrets projected volume readonly error
  config/prow/config.yaml
Labels: approved, size/XS

#19 Add console postsubmits job
  config/jobs/kubesphere/console/console-postsubmits.yaml
Labels: approved, lgtm, size/M

#21 fix docker credential mount location
  config/jobs/kubesphere/kubesphere/kubesphere-postsubmits.yaml
  config/prow/config.yaml
Labels: approved, size/S
