Repository kubesphere/test-infra, pull requests merged in 2021-08, with the labels that each got.

#22 update OWNERS
  OWNERS
Labels: approved, size/XS

#23 add branch validation for console job
  config/jobs/kubesphere/console/console-postsubmits.yaml
  config/jobs/kubesphere/console/console-presubmits.yaml
Labels: lgtm, approved, size/XS

#24 Add milestone plugins for kubesphere/ks-devops repo
  config/prow/plugins.yaml
Labels: lgtm, approved, size/XS

#25 add label sync job
  config/jobs/kubesphere/test-infra/test-infra-postsubmits.yaml
  config/prow/Makefile
  config/prow/labels.yaml
Labels: approved, size/L

#26 token throttled due to large number of repos under org, sync only selected repos
  config/jobs/kubesphere/test-infra/test-infra-postsubmits.yaml
Labels: approved, size/XS

#27 Add label require-ui-text-review.
  config/prow/labels.yaml
Labels: lgtm, size/S, approved

#28 Change description of label require-ui-text-review to fix a problem.
  config/prow/labels.yaml
Labels: lgtm, approved, size/XS
