Repository kubesphere/test-infra, pull requests merged in 2021-12, with the labels that each got.

#35 Add console preview
  config/jobs/kubesphere/console/console-presubmits.yaml
  config/prow/config.yaml
  images/build-tools-lite/Dockerfile
  images/build-tools-lite/build-and-push.sh
Labels: approved, size/L

#36 fix job typo
  config/prow/config.yaml
Labels: approved, size/XS

#38 add multi arch preset labels
  config/jobs/kubesphere/console/console-postsubmits.yaml
Labels: approved, size/XS

#39 add periodic refresh l10n
  config/jobs/kubesphere/console/console-postsubmits.yaml
Labels: approved, size/M

#40 change console build image repo to dev
  config/jobs/kubesphere/console/console-postsubmits.yaml
  config/jobs/kubesphere/console/console-presubmits.yaml
Labels: approved, size/XS

#41 fix console postsubmit build
  config/jobs/kubesphere/console/console-presubmits.yaml
Labels: approved, size/XS

#42 add preset label
  config/jobs/kubesphere/console/console-presubmits.yaml
Labels: approved, size/XS

#43 run build on tagging
  config/jobs/kubesphere/console/console-postsubmits.yaml
Labels: approved, size/XS

#44 Add plugin release-note and require-matching-label to ks-devops
  config/prow/plugins.yaml
Labels: lgtm, approved, size/XS
