Repository kubesphere/test-infra, pull requests merged in 2022-01, with the labels that each got.

#45 Add the config of openelb
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: size/S

#48 Make default merge_method of kubesphere/ks-devops be squash
  config/prow/config.yaml
Labels: lgtm, size/XS

#46 Add tide & label-sync to openelb
  config/jobs/kubesphere/test-infra/test-infra-postsubmits.yaml
  config/prow/config.yaml
Labels: lgtm, size/S, approved

#49 add guofeng to OWNERS
  OWNERS
Labels: approved, size/XS
